name: "publish-image"
description: "Composite action to publish complyscribe images."

inputs:
  image:
    required: true
    description: The image repository location in the format of registry/name/app
  release_version:
    required: true
    description: The version to build type semver tags from
  no_cache:
    description: Skip using cache when building the image.
    required: false
    default: "false"
  skip_tests:
    description: Skip pre-push testing
    required: false
    default: "false"
outputs:
  image_sha:
    value: ${{ inputs.image }}@${{ steps.build-and-push.outputs.digest }}
    description: The published image with digest

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # pin@v4.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # pin@v3

    # Tags are defined here based on workflow triggers
    - name: Define metadata
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # pin@v6.0.0
      with:
        images: ${{ inputs.image }}
        tags: |
          type=semver,pattern=v{{major}},enable=${{ !startsWith(inputs.release_version, 'v0.') }},value=${{ inputs.release_version }}
          type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.release_version }}
          type=semver,pattern=v{{version}},value=${{ inputs.release_version }}
          type=raw,value=${{ inputs.release_version }}-{{branch}}-{{sha}},enable=${{ github.event_name == 'workflow_dispatch' }}
          type=schedule,pattern={{date 'YYYYMMDD'}},prefix=${{ inputs.release_version }}.
        flavor: |
          latest=false

    - name: Build and export to Docker
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # pin@v5
      id: build-and-export
      with:
        context: "."
        load: true
        no-cache: ${{ inputs.no_cache == 'true' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Pre-push Image Scan
      uses: aquasecurity/trivy-action@97e0b3872f55f89b95b2f65b3dbab56962816478 # pin@0.34.2
      with:
        image-ref: ${{ inputs.image }}:${{ steps.meta.outputs.version }}
        exit-code: 1
        skip-files: "**/.venv/lib/**/METADATA"
        scanners: secret
        severity: HIGH,CRITICAL,MEDIUM

    - name: Pre-push testing
      if: ${{ inputs.skip_tests == 'false' }}
      uses: ./.github/actions/e2e-testing
      with:
        image: "docker-daemon:${{ inputs.image }}:${{ steps.meta.outputs.version }}"
        build: false

    # Does not rebuild. Uses internal cache from previous step.
    - name: Build and Push
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # pin@v5
      id: build-and-push
      with:
        context: "."
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
